
// FOR AUTH DATA
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
export const REGISTER = "REGISTER"
export const SET_USER_TOKEN = "SET_USER_TOKEN"
export const SET_USER_DATA = "SET_USER_DATA"

// FOR GLOBAL STATE OF LOADER
export const LOADING_TRUE = "LOADING_TRUE"
export const LOADING_FALSE = "LOADING_FALSE"

// FOR ALL USER DATA
export const SET_COMPANIES = "SET_COMPANIES"

// FOR USER DATA
export const SET_USER_DETAILS = "SET_USER_DETAILS"
export const SET_USER_SHARES = "SET_USER_SHARES"
